[build]
  command = "NODE_ENV=development rm -rf node_modules && NODE_ENV=development npm install --legacy-peer-deps && NODE_ENV=production npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

