[build]
  command = "npm install --legacy-peer-deps --ignore-scripts && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_DISABLE_TELEMETRY = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

