[build]
  command = "npm install --legacy-peer-deps && NODE_OPTIONS='--max-old-space-size=4096' npx next build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.19.0"
  SECRETS_SCAN_ENABLED = "false"

# Removed Next.js plugin for static export

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

