# Netlify Configuration for ReLoop Platform

[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  # Node version for builds
  NODE_VERSION = "18"
  
  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Enable Next.js standalone output
  NEXT_PRIVATE_STANDALONE = "true"

# Essential plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Enhanced security headers
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), payment=()"
    
    # CORS headers for API
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Access-Control-Allow-Origin = "*"

# Redirects for API routes (if using Netlify Functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false

# Handle trailing slashes - removed conditions due to Netlify parsing issue
# [[redirects]]
#   from = "/*"
#   to = "/:splat/"
#   status = 301
#   force = false

# Environment-specific contexts
[context.production]
  environment = { NODE_ENV = "production" }
  
[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://reloop.eco"
  NEXT_PUBLIC_API_URL = "https://reloop.eco/api"
  NEXT_PUBLIC_WS_URL = "wss://reloop.eco"

[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  
[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Post-processing optimizations - simplified
# Next.js handles its own optimization, so we skip Netlify's processing
[build.processing]
  skip_processing = true

# Edge Functions (if needed)
# [[edge_functions]]
#   path = "/api/*"
#   function = "api-handler"
